### PR TITLE
Depth camera sonar

### PR DESCRIPTION
**Pull request by BruceMty**
Sonar is introduced.  This is posted for review and is not ready to merge.

* Normal angles are read by Gazebo but are not used in Power equations.
* Ray dimensions are not synchronized between the Gazebo camera SDF and the equations.  They are hardcoded on the SDF and Python sides.  Currently Python is hardcoded for one beam but can be hardcoded for multiple beams.
* Output is a 2D ROS Image where the first axis is the beam number, the second axis is the distance bucket number and the value is the power sum for that bucket for that beam.

To do:
* Add a "diagnostics" point cloud where axis 1 is range, axis 2 is sonar_retro, and axis 3 is the normal angle.
* Scale bucket time ranges to distance ranges.
* Integrate normal angles.

To run:  type:

    roslaunch nps_uw_sensors_gazebo depth_camera_sonar_basic.launch

Depth camera settings are set in file `urdf/depth_camera_sonar_robot.xacro`.  Sonar settings are hardcoded in file `scripts/sonar_equations.py`.  File `scripts/sonar_ros.py` runs the ROS Node that sends and receives ROS messages and calls `scripts/sonar_equations.py` to perform the math.

### CODE REVIEW

**Comment by BruceMty** [comment]
At this point, Normal angles are read, but the incidence angle can return values that are out of range, see sonar_equations.py function `_ray_incidence`.  Specifically, we are getting target normal values of xyz=0,0,0 and xyz=-1,-1,0, which are invalid because they do not represent unit distances.

The Sonar equations can be run two ways:

* Directly, with a hardcoded dataset, type `./sonar_equations.py`, see `__main__`.
* Using Gazebo, type `roslaunch nps_uw_sensors_gazebo depth_camera_sonar_basic.launch`.

Future work:

* To aid in diagnostics, I'll add an "image" topic where the points correspond to normal angles for rays.
* Code needs refactored to maximize initialization calculations and minimize runtime calculations.
* We need to simplify computational complexity.  In particular to not iterate over 100K+ frequencies for each ray processed.

**Comment by M1chaelM** [comment]
Bruce,

The most obvious this to ask about normal values of 0,0,0 is what the range value is. That response only makes sense if the ray doesn't strike anything, or if whatever it strikes is outside the allowable range of the sensor.

Regarding -1,-1,0: I'm surprised to see that the depth camera is returning this, but if it is we should check that it is plausible for whatever object we are striking. Assuming these are the depth-camera coordinates before they have been translated, it suggests the face of the object is parallel to the camera. As long as the direction is really correct and this is expected behavior, it's not a problem to translate to a vector of unit length.

**Comment by BruceMty** [comment]
A normals memory copy error was corrected.  Here are some values for a single-beam test case 3 rays wide and 4 rays high:

    Incidence angles:
    1.695266, 1.570796, 1.570796
    1.695332, 1.570796, 1.570796
    1.695259, 1.604963, 1.604963
    1.638297, 1.638297, 1.638297
    
    Ray distances:
    1.193127, 7.000000, 7.000000
    1.193126, 7.000000, 7.000000
    1.193126, 2.889497, 2.893409
    0.961657, 0.962388, 0.962388
    
    Ray Normals column by row by (x,y,z):
    
    ray normal 0: 0.173651, 0.984807, -0.000000
    ray normal 0: 0.000000, 0.000000, 0.000000
    ray normal 0: 0.000000, 0.000000, 0.000000
     
    ray normal 1: 0.173651, 0.984807, -0.000000
    ray normal 1: 0.000000, 0.000000, 0.000000
    ray normal 1: 0.000000, 0.000000, 0.000000
     
    ray normal 2: 0.173651, 0.984807, -0.000000
    ray normal 2: 0.000000, -0.000000, -1.000000
    ray normal 2: 0.000000, -0.000000, -1.000000
     
    ray normal 3: 0.000000, -0.000000, -1.000000
    ray normal 3: 0.000000, -0.000000, -1.000000
    ray normal 3: 0.000000, -0.000000, -1.000000

Run by typing `roslaunch nps_uw_sensors_gazebo depth_camera_sonar_basic.launch`.  The bucketed Sonar beam power image is published as `sonar_beam_image`.  The incidence angles are published as `sonar_ray_incidence_image`.

I question the correctness of the incidence angles.  I would expect they would vary more.

Code still contains diagnostics.

**Comment by BruceMty** [comment]
Regarding CI Lint check on file src/nps_gazebo_ros_depth_camera_sonar_single_beam.cpp: This file is adapted from ROS Melodic file gazebo_ros_pkgs/gazebo_plugins/src/gazebo_ros_depth_camera.cpp.  It is modified to additionally forward normals data.  I recommend exempting this file from lint checks because leaving it alone preserves its similarity to the file it came from.  Lint is producing 112 errors.

**Comment by BruceMty** [comment]
A Sonar image is now created along with several diagnostic images and views.  Ray dimensions and sonar parameters are hardcoded in `scripts/sonar_equations.py`.  These ray dimensions must match the ray dimensions provided to the depth camera.  Please refer to the write-up and demo at https://github.com/Field-Robotics-Lab/dave/wiki/Depth-Camera-Sonar-with-Normals.

**Comment by woensug-choi** [comment]
Getting error msg launching with `roslaunch nps_uw_sensors_gazebo depth_camera_sonar_basic.launch`
```bash
process[depth_and_normals_to_sonar-5]: started with pid [4391]
/usr/bin/env: ‘python\r’: No such file or directory
process[rqt_image_view_image_beams-6]: started with pid [4392]
[depth_and_normals_to_sonar-5] process has died [pid 4391, exit code 127, cmd /home/eric/uuv_ws/src/nps_uw_sensors_gazebo/scripts/sonar_ros.py __name:=depth_and_normals_to_sonar __log:=/home/eric/.ros/log/8a5c2930-fba5-11ea-9dd5-bcee7b8ddb04/depth_and_normals_to_sonar-5.log].
log file: /home/eric/.ros/log/8a5c2930-fba5-11ea-9dd5-bcee7b8ddb04/depth_and_normals_to_sonar-5*.log
```
according to [this thread](https://askubuntu.com/questions/896860/usr-bin-env-python3-r-no-such-file-or-directory)
`The problem are your line ending characters. Your file was created or edited on a Windows system and uses Windows/DOS-style line endings (CR+LF), whereas Linux systems like Ubuntu require Unix-style line endings (LF).`
using package dos2unix with command `dos2unix *.py` fixed the problem which is installed with `sudo apt install dos2unix`. Maybe this can also solve github compile check error.

**Comment by woensug-choi** [comment]
Concerning high computational costs, excluding the point scatter model and process solely the sonar equation makes a significant reduction in calculation time. Transforming the data between frequency and time domain consumes lots of resources. @bsb808 Being very careful with this topic and hoping that I would not hurt anyone by accident, I asked a few times for the reason why we need the point scattering model to Andi. Without getting any answers, I thought it's needed for her thesis to include something new. Wondering how much fidelity is needed and what the model can provide, I think it's better to exclude it for our purposes. Or find a way to parallelize the sonar computation.

@BruceMty I have added the python code without the point scattering model on [sonar_re_noScatteringModel_v1.py](https://github.com/Field-Robotics-Lab/matlab_sonar_prototype/blob/master/sonar_re_noScatteringModel_v1.py). It needs more revisions for what values should be used as parameters (e.g. source level, noise amplitude). Comparing with the previous python code (which takes about 2 seconds for main calculations), the new script takes less than 0.01 seconds to run. Two codes do not show exactly the same results at the moment. But it still would be able to distinguish objects with relative echo levels.

image

**Comment by BruceMty** [comment]
@woensug-choi thank you for providing this.  This will address the computational cost issue.  I would like @bsb808 to comment on any impact on loss of fidelity.

Because of Python looping, I can expect a 100x speedup by porting the existing algorithm to C++.  But I strongly encourage computational simplification where possible.

@bsb808 , @M1chaelM at this point would you recommend I port one of these approaches to C++?

**Comment by bsb808** [comment]
I spoke with @woensug-choi about this and think I understand that the current situation is that...

The python implementation of the sonar model runs very slowly.  https://github.com/Field-Robotics-Lab/dave/wiki/Depth-Camera-Sonar-with-Normals reports that it takes ~10s to generate a sonar scan for a scenario with a reduced number of rays/beams.

The point scattering model is a very important part of our current sonar model.  We can't throw it out without a viable alternative to capture similar interactions.

My recommendation is to not make this PR contingent upon running in real-time.  We should just verify that the python node correctly implements the mathematical model.  Before merging the PR we should describe the computational issues as a new github issue for post 2.0.0.

Implementing this in a computationally viable way will likely take some design.  Simply porting to C++ may not be sufficient - we may need to consider other options such as parallelization.

**Comment by BruceMty** [comment]
I added https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/issues/18 to document the need to improve performance.

We need to fix or disable Lint issues.  Are there any other issues blocking merging this PR?

**Comment by M1chaelM** [comment]
@BruceMty Is there a reason not to move the header to an include directory?

**Comment by BruceMty** [comment]
@M1chaelM Being prototype code, I put headers in src for ease of working with.  ROS separates headers.  Gazebo puts them together.  I can move the headers if you like.

**Comment by M1chaelM** [comment]
> @M1chaelM Being prototype code, I put headers in src for ease of working with. ROS separates headers. Gazebo puts them together. I can move the headers if you like.

Great, thanks. Yes, could you put them under the include directory?

**Comment by M1chaelM** [comment]
Lint issues are resolved and this is now passing checks. I am not caught up on the conversation between @BruceMty and @woensug-choi above. Is @woensug-choi the reviewer?

**Review by woensug-choi — APPROVED** [review]
As a review for current PR, in summary, I was able to reproduce what was on the wiki page.
Additional tests by changing beam numbers at both `depth_camera_sonar_robot.xacro` and `sonar_equations.py` lead to change in sonar image resolution as expected. 

**Assuming that the issues already been discussed in the PR comments will be addressed later for release 3.0 in C++ implementations, the current PR is approvable.**

A strange error was found for the python script text format. `dos2unix *.py` for three python scripts fixed the errors. I was not able to make a commit since the Github status says 'No content changes found' but says '3 changed files' at the same time. I don't think this issue should block this PR, since C++ implementation is expected.

**Comment by BruceMty** [comment]
> A strange error was found for the python script text format. `dos2unix *.py` for three python scripts fixed the errors. I was not able to make a commit since the Github status says 'No content changes found' but says '3 changed files' at the same time. I don't think this issue should block this PR, since C++ implementation is expected.

@woensug-choi What was the strange error?  Why did you run dos2unix.py?  I ran dos2unix.py.  It did not change any content but it did update the timestamp of the files.

**Comment by BruceMty** [comment]
> As a review for current PR, in summary, I was able to reproduce what was on the wiki page.
> Additional tests by changing beam numbers at both `depth_camera_sonar_robot.xacro` and `sonar_equations.py` lead to change in sonar image resolution as expected.

@woensug-choi how were you able to verify the Sonar component if it gave this error?  How can we troubleshoot this?  Is your build environment clean, e.g. "catkin_make clean; catkin_make"?

**Comment by M1chaelM** [comment]
@BruceMty, @woensug-choi has documented the problem you ask about in issue #19. It appears to be relatively minor. Let's move further discussion to that issue and submit a new PR if needed.

Since this has been reviewed and approved, I am merging the PR.

**Pull request merged**
