### PR TITLE
move target further than 2 meters, align collision element, improve mesh

### PR DESCRIPTION
**Pull request by BruceMty**
The target is moved further than 2 meters to meet FLS minimum distance, allowing the target to be observable.  The simpler P900 mesh is used.  Collision orientation is corrected.  M450 mass is adjusted.

In future, the Sonar source point should be adjusted to align with the visual model rather than coming from their centers.

Reference: https://github.com/Field-Robotics-Lab/dave/wiki/fls_model_standalone#fls-models

### CODE REVIEW

**Comment by bsb808** [comment]
The wiki says, "BlueView P900: Scan is 90 degrees horizontal by 20 degrees vertical. Horizontal scan is 256 points, each one degree wide and 20 degrees tall resulting in a 90 degree view. "  
This doesn't make sense to me; I would expect 90, 1 degree beam to represent 90 degree horizontal field of view.

**Comment by bsb808** [comment]
> The wiki says, "BlueView P900: Scan is 90 degrees horizontal by 20 degrees vertical. Horizontal scan is 256 points, each one degree wide and 20 degrees tall resulting in a 90 degree view. "
> This doesn't make sense to me; I would expect 90, 1 degree beam to represent 90 degree horizontal field of view.

**Comment by BruceMty** [comment]
The physical BlueView P900 device scans horizontally 90 degrees.  There are 256 beams across this horizontal scan.  Each beam is axially asymmetric, a fraction of a degree wide by 20 degrees tall.

To represent this with the modeler, we configure a grid of rays that span 90 degrees horizontally and 20 degrees vertically.  We tune it with 256 rays horizontally and 256*(20/90) points vertically.

The Wiki is updated with this clarification.

**Comment by bsb808** [comment]
Sorry for closing the PR - accident.  Should be re-open.

**Comment by bsb808** [comment]
Selection_044

The receive axes for the Seabat device is the blue vector - not the red vector.

**Comment by bsb808** [comment]
Other than the coordinate frame issue with the Seabat, I ran the three examples without any issues.  Once that is addressed, ready to merge.

I'll look into the wiki description and propose something here.

**Comment by BruceMty** [comment]
Thanks for helping clarify the Wiki.

I changed the SeaBat orientation.  Recall that there are two parts and we show only one.  @bsb808 , if you get the chance, please check the orientation of the inertial component.   The Gazebo Inertia view did not indicate anything.

**Comment by bsb808** [comment]
@BruceMty   I pushed changes to the wiki.  The imaging sonar plugin doesn't to a terribly good job of capturing the sonar geometry, so it is tough to match them up.

Did you push the commit with the changed orientation?

> Thanks for helping clarify the Wiki.
> 
> I changed the SeaBat orientation. Recall that there are two parts and we show only one. @bsb808 , if you get the chance, please check the orientation of the inertial component. The Gazebo Inertia view did not indicate anything.

**Comment by bsb808** [comment]
Can you check the names of the sonar models in the world file?

In the seabat world the model is still named "blueview_p900".

https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/blob/110fc4fd554fd3498653f4044af71d85c38a1dcc/worlds/sonar_tank_seabat_f50.world#L34

**Comment by BruceMty** [comment]
@bsb808 , now pushed.

**Comment by BruceMty** [comment]
Good chatch, seabat model name fixed.

**Comment by bsb808** [comment]
The seabat orientation looks good.  Here is my calculation for the moment of inertia values based on the mass and dimensions - see https://en.wikipedia.org/wiki/List_of_moments_of_inertia


[sensor_moment_of_inertia.zip](https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/files/4749015/sensor_moment_of_inertia.zip)

**Comment by bsb808** [comment]
Looks good - merge when you are ready!

**Review by bsb808 — APPROVED** [review]
Good to go.

**Comment by BruceMty** [comment]
@bsb808 , It is not clear how hwd maps to xyz so it is not clear whether inertia is correct.

**Comment by bsb808** [comment]
In the spreadsheet I sent the xx, yy, and zz axes map to the axes and shown in gazebo (RBG).  It looks to be consistent with 181104e

**Pull request merged**
