### PR TITLE
Added DVL gradient estimation example

### PR DESCRIPTION
**Pull request by crvogt**
### DVL-based seabed gradient estimation example. (To be accompanied by wiki entry)

Allows a user to launch and move a standalone DVL sensor model in an ocean world the seabed for which contains known slope values. Plots measured gradient values in real time.

Two examples are available, one with the UUV Simulator DVL, and the other with the WHOI DVL.

The examples are started by running
```
roslaunch nps_uw_sensors_gazebo whoi_teledyne_whn_standalone_gradient.launch 
```
or
```
roslaunch nps_uw_sensors_gazebo uuvsim_teledyne_whn_standalone_gradient.launch
```

Both spawn a DVL model in the `graded_seabed.world`, as well as launching three other nodes:
```
/twist_keyboard
/twist_dvl_state
/plot_gradient
```
##### Publishes 
```
/cmd_vel
```
is used to send twist messages to the gazebo model.

##### Subscribes to
(uuv_sim based)
```
/dvl/dvl_sonar0
/dvl/dvl_sonar1
/dvl/dvl_sonar2
/dvl/dvl_sonar3
/gazebo/model_states
/cmd_vel
``` 
(whoi_based)
```
/dvl/dvl
/gazebo/model_states
/cmd_vel
```
##### Publishes
```
/dvl_gradient
```
applies the twist message to the model and estimates the gradient

##### Subscribes to
```
/gazebo/model_states
/dvl_gradient
```
generates a figure and plots gradient magnitude, direction, and error.

### CODE REVIEW

**Comment by lauralindzey** [comment]
I was looking for an example of getting the WHOI dvl plugins working, and came across this PR. 

Confusingly, it appears that the file named "whoi_teledyne_whn_standalone_gradient.launch" actually starts the uuv_simulator DVL plugin, rather than the WHOI one.

**Comment by crvogt** [comment]
> I was looking for an example of getting the WHOI dvl plugins working, and came across this PR.
> 
> Confusingly, it appears that the file named "whoi_teledyne_whn_standalone_gradient.launch" actually starts the uuv_simulator DVL plugin, rather than the WHOI one.

Correct, I wrote the launch file name before realizing there were two DVL models and forgot to update it. I'll commit an example for both.

Thanks for pointing it out.

**Comment by crvogt** [comment]
@lauralindzey I've added a WHOI DVL example which can be run via `roslaunch nps_uw_sensors_gazebo whoi_teledyne_whn_standalone_gradient.launch`, though at the moment it spawns attached to a UUV. Applying a rotation using the `teleop_twist_keyboard` node will induce a roll followed by incorrect slope values, so until I correct it the model works fine with strafing (movement with caps-lock on). I'll update the wiki as well once I am spawning the sensor alone.

**Comment by lauralindzey** [comment]
Thanks @crvogt! I've pulled and it seems to be working as described.

**Comment by crvogt** [comment]
@dtdavi1 Hey Duane, would you mind reviewing this when you have a moment?

**Review by dtdavi1 — APPROVED** [review]
Everything looks correct as far as I can tell.  The wiki entry provides a good description of how to run everything and what to expect (once it occurred to me to look there).  Very happy to see that it works with both the WHOI DSL plugin and the UUV Simulator plugin.

**Pull request merged**
