### PR TITLE
[Branch on origin repo for #37 and #38] Fix sonar connect count and Sensor gain handle

### PR DESCRIPTION
**Pull request by woensug-choi**
This is a new branch on the original repo concerning https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/pull/37 which is made on forked repo

@lauralindzey I made some generic fixes on this subject. 
- Remove duplicate sonar image publisher
- Remove sonar topic connection counter
- Make it recognize sonar topic connection as a depth camera topic connection
It was originated from the duplicate publishers of sonar image. I've removed one of them. Also removed sonar image counters which could not be utilized. The parent depth plugin code of the gazebo only has new depth image detection child functions. I have connected the new sonar image topic connection direct to the new depth image connection.

### CODE REVIEW

**Comment by lauralindzey** [comment]
@woensug-choi - I just tested, and this works for me. Thanks!

**Comment by woensug-choi** [comment]
@crvogt Could you review this PR? The functionality is already been checked by Laura. What it's trying to fix is to make the plugin able to run solely on sonar topic subscription.
- Previous : It needed to view depth camera data (depth_image, real_image, normal_image) to process sonar equation. With a sonar viewer only, the sonar calculation would not be performed.
- Modified : Even with a sonar viewer the only case, the plugin recognizes it as a depth camera data subscription to run everything.

**Comment by woensug-choi** [comment]
Packaging https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/pull/38 in this PR.
Added a `sensorGain` at sdf configuration handle to scale raw sonar data. The default value for the `plotScaler` is changed accordingly for the bundled viewer. This change does not collide with any other parts of the code.

**Comment by woensug-choi** [comment]
Closing this since it's included in https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/pull/44

**Pull request closed without merging**
