### PR TITLE
add FLS models

### PR DESCRIPTION
**Pull request by BruceMty**
Presently not ready to merge.  SeaBat f50 .png may not be being accessed.  BlueView has "hollow" spots in power plug.  Also, collision and physics properties are not ready.

### CODE REVIEW

**Comment by bsb808** [comment]
In order to have gazebo be aware of the models you'll need to add the following to the package.xml file 
```
 <export>
    <gazebo_ros gazebo_model_path="${prefix}/models"/>
    <gazebo_ros gazebo_media_path="${prefix}"/>
  </export>
```
See the `dave/uuv_dave/package.xml` for an example.

**Comment by M1chaelM** [comment]
> In order to have gazebo be aware of the models you'll need to add the following to the package.xml file
> 
> ```
>  <export>
>     <gazebo_ros gazebo_model_path="${prefix}/models"/>
>     <gazebo_ros gazebo_media_path="${prefix}"/>
>   </export>
> ```
> 
> See the `dave/uuv_dave/package.xml` for an example.

I believe this is also already done on the uwlidar branch.

**Comment by bsb808** [comment]
Currently waiting on updated meshes / textures and updated physical params.

**Comment by BruceMty** [comment]
We additionally need gazebo_ros to make the export work:

  <depend version_gte="2.5.17">gazebo_ros</depend>
  <export>
    <gazebo_ros gazebo_model_path="${prefix}/models"/>
    <gazebo_ros gazebo_media_path="${prefix}"/>
  </export>

**Comment by BruceMty** [comment]
Currently only waiting on meshes / textures.  Physical parameters are done and example launch files are in place.

**Comment by BruceMty** [comment]
Meshes are in place.  In future we may want a simpler P900 mesh and we may want to patch minor holes in the M450 and F50 meshes views.

**Pull request merged**
