### PR TITLE
Fix install so sonar_ros.py works under Noetic

### PR DESCRIPTION
**Pull request by lauralindzey**
In #29, @crvogt pointed out that I had missed installing sonar_ros.py and that it is used by `depth_camera_sonar_basic.launch`. Since that PR has already been merged, I went ahead and created a new one. 

The fix is slightly more complicated than just adding the script to catkin_install_python(), since sonar_ros.py imports sonar_equations. Since it's an imported module rather than a script, its directory needs an `__init__.py` and we need to add a setup.py so it's properly installed by catkin (see http://docs.ros.org/en/api/catkin/html/howto/format2/installing_python.html)

Based on the ROS documentation, sonar_equations.py would preferably be under src/, and would be imported as `package_name.module_name` rather than just `module_name`. However, I didn't change this, since the src/scripts/nodes directory conventions don't seem to be particularly strong ones, and I'm trying to keep the noetic-supporting changes as small as possible.

I tested on Noetic, and `roslaunch nps_uw_sensors_gazebo depth_camera_sonar_basic.launch` now works for me.

### CODE REVIEW

**Comment by lauralindzey** [comment]
The failing test appears to be due to a dependency on acoustic_msgs that was introduced in #25; tests also failed on that PR.

**Comment by crvogt** [comment]
@lauralindzey Thanks! Just wanted to check, you mentioned `depth_camera_sonar_basic.launch` is working for you. Are you getting any errors on startup?

**Comment by lauralindzey** [comment]
Interesting.

I had originally tested this fix before the new imaging sonar work was merged in; after your question, I merged in the most recent master branch, and tried again:
~~~
cd ~/dave_ws
rm -rf devel build
catkin build
roslaunch nps_uw_sensors_gazebo depth_camera_sonar_basic.launch
~~~

It now fails with:
~~~
[Err] [Plugin.hh:178] Failed to load plugin libnps_gazebo_ros_depth_camera_sonar_single_beam_plugin.so: libnps_gazebo_ros_depth_camera_sonar_single_beam_plugin.so: cannot open shared object file: No such file or directory
~~~

It looks like sometime between commit 46ccff0 and f49df01 the .so file stopped being built? I might not have caught it in my earlier testing if I didn't remove my devel & build directories... and I can't test any versions between those because they don't build on my machine.

I tried cherry-picking my changes to 46ccff0, and the launch file starts cleanly in the older version.

**Comment by crvogt** [comment]
>It now fails with:

Thanks for testing that, I'm coming up with the same error. I'll track it down/discuss what's happening. As far as I can tell, this PR is fine; I'd like to straighten things out on our end before I approve it.

**Comment by woensug-choi** [comment]
Quoting a part of the reply that I've sent to @crvogt 

> First things first, the python scripts are written with Bruce and me before working with Duane. The python scripts were supposed to be the step-by-step development trails starting from MATLAB->Python->C++. Bruce left after initial Python scripts merged into the master. Thereafter, we have discussed out starting again from MATLAB again with Derek's MATLAB demonstration codes of his theory. After that, Duane and I worked right to C++ plugin without Python trials. In conclusion, the python scripts 'sonar_equations.py', 'sonar_ros.py', 'depth_camera_sonar.py' are not being used for the last merged PR of our final good-looking PR at all. It should be deleted.

@lauralindzey Are you using any of those python scripts?

**Comment by lauralindzey** [comment]
@woensug-choi  - Nope; I'm only hoping to use the final plugin.

I only came across the scripts because I was running the various launch files to try to test my Noetic install. If they only existed for development, feel free to rearrange/delete/whatever without worrying about me.

**Comment by woensug-choi** [comment]
I've added another PR https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/pull/43 to remove redundant scripts, launch files and others concerning this PR.

**Pull request closed without merging**
