### PR TITLE
Standalone Underwater Lidar Demo

### PR DESCRIPTION
**Pull request by M1chaelM**
Some refinements and corrections to the underwater lidar standalone demo in the empty tank environment. To test, please refer to this[ 3D Underwater Lidar Tutorial](https://github.com/Field-Robotics-Lab/dave/wiki/3D-Underwater-Lidar) in the dave Wiki.

### CODE REVIEW

**Comment by M1chaelM** [comment]
To test, please follow the tutorial at: https://github.com/Field-Robotics-Lab/dave/wiki/3D-Underwater-Lidar

**Comment by BruceMty** [comment]
Should numbers in https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/pull/10/files#diff-6224aea3f6a427bad1cc9704ae52dc2c be checked?  At a glance, this file seems fine.

Regarding the tutorial: Nice work.  Under Visualizing with rviz Step 1: It may be cleaner to tell the user to "cd ~/uuv_ws" rather than to always suggest it.  i.e. no "For example".  In this case, I believe we can remove Step 1 and in Step 4 get rid of "If you are..." and put "cd ~/uuv_ws" in front of the "rosrun" line.  But maybe I'm expecting too much of the user.

At step 4 my target is magenta, not red.  After setting the position dynamically, I get this:
PR10.  The picture shows all rays striking the wall and rays on the left passing through the wall; I expected rays to stop at the wall.  The point cloud on the right shows two separate patches of points, I expected one patch.  Please add text to explain.

Fix text "$0$".

**Comment by M1chaelM** [comment]
> Should numbers in https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/pull/10/files#diff-6224aea3f6a427bad1cc9704ae52dc2c be checked? At a glance, this file seems fine.

Bruce, you are welcome to check them. They have changed due to the new dimensions, and are calculated using the moments of inertia for cylinders (based on the collision model dimensions): https://en.wikipedia.org/wiki/List_of_moments_of_inertia

> 
> Regarding the tutorial: Nice work. Under Visualizing with rviz Step 1: It may be cleaner to tell the user to "cd ~/uuv_ws" rather than to always suggest it. i.e. no "For example". In this case, I believe we can remove Step 1 and in Step 4 get rid of "If you are..." and put "cd ~/uuv_ws" in front of the "rosrun" line. But maybe I'm expecting too much of the user.

I appreciate the review and will take a look, but generally let's not make approval of the PR dependent on the perfection of the tutorial. The tutorial is attached to the PR just to make it easier to do the review. If the code seems to be working, please approve, and then we can fix the tutorial separately.

> 
> At step 4 my target is magenta, not red. After setting the position dynamically, I get this:
> PR10. The picture shows all rays striking the wall and rays on the left passing through the wall; I expected rays to stop at the wall. The point cloud on the right shows two separate patches of points, I expected one patch. Please add text to explain.

This is weird, but I think we should file it as an issue rather than block the PR. What seems to be happening is that the Lidar has a minimum and maximum range, which I set to correspond to the specs of the SL3 this is based on. It looks like Gazebo doesn't calculate collisions until the beginning of the minimum range, which suggests it is expecting this setting to be used just to avoid having a sensor collide with it's own physical casing. On the other hand, it's promising that the output is a different color, since that indicates we can distinguish between the two cases. At any rate, this is a question our Open Robotics friends can help with, so I will open an issue for it.
 
> 
> Fix text "$0$".

If you spot typos or have ideas for improving the tutorial that are not controversial, please just make them yourself. Sending a request back to the author requires too many round trips for simple changes like this. Again, this is partly because the tutorial is not part of the pull request, but rather a complimentary effort that is referenced to help speed up testing.

**Comment by BruceMty** [comment]
Okay.

**Review by BruceMty — APPROVED** [review]

**Comment by M1chaelM** [comment]
Following up: 
* I reviewed and edited the tutorial.
* I created issue #12 to capture the behavior you describe and will see if someone from OR can take a quick look next week.
* I'm now merging this PR.

**Comment by crvogt** [comment]
@M1chaelM Leaving branch until #12 is closed.

**Pull request merged**
